import { Inter } from "next/font/google";
import "./globals.css";
import UserProvider from "./userProvider";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title:{
    absolute : "" ,
    default : "AISHA",
    template :"%s | AISHA"

  },
  description: "Generated by create next app",
};

export default function RootLayout({ children ,
            navBar,
            produits,
            eventProduits
}) {
  
  return (
    <html lang="en">
      <UserProvider>
        
      <body className={inter.className}>
        <nav>
          {navBar}
        </nav>
        <main className="flex ">
              {children}
              <div className="flex flex-col overflow-hidden  ">
                { eventProduits}
                {produits}
            </div>
        </main>
         

        
      </body>
      </UserProvider>
    
    </html>
  );
}
